package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_ClusterVersionProgressInsight = map[string]string{
	"":       "ClusterVersionStatusInsight reports the state of a ClusterVersion resource (which represents a control plane update in standalone clusters), during the update.",
	"spec":   "spec is empty for now, ClusterVersionStatusInsight is purely status-reporting API. In the future spec may be used to hold configuration to drive what information is surfaced and how",
	"status": "status exposes the health and status of the ongoing cluster update",
}

func (ClusterVersionProgressInsight) SwaggerDoc() map[string]string {
	return map_ClusterVersionProgressInsight
}

var map_ClusterVersionProgressInsightList = map[string]string{
	"":      "ClusterVersionProgressInsightList is a list of ClusterVersionProgressInsightList resources\n\nCompatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.",
	"items": "items is a list of ClusterVersionStatusInsight resources",
}

func (ClusterVersionProgressInsightList) SwaggerDoc() map[string]string {
	return map_ClusterVersionProgressInsightList
}

var map_ClusterVersionProgressInsightSpec = map[string]string{
	"": "ClusterVersionProgressInsightSpec is empty for now, ClusterVersionProgressInsightSpec is purely status-reporting API. In the future spec may be used to hold configuration to drive what information is surfaced and how",
}

func (ClusterVersionProgressInsightSpec) SwaggerDoc() map[string]string {
	return map_ClusterVersionProgressInsightSpec
}

var map_ClusterVersionProgressInsightStatus = map[string]string{
	"conditions":           "conditions provides detailed observed conditions about ClusterVersion",
	"resource":             "resource is the ClusterVersion resource that represents the control plane\n\nNote: By OpenShift API conventions, in isolation this should be a specialized reference that refers just to resource name (because the rest is implied by status insight type). However, because we use resource references in many places and this API is intended to be consumed by clients, not produced, consistency seems to be more valuable than type safety for producers.",
	"assessment":           "assessment is the assessment of the control plane update process",
	"versions":             "versions contains the original and target versions of the upgrade",
	"completion":           "completion is a percentage of the update completion (0-100)",
	"startedAt":            "startedAt is the time when the update started",
	"completedAt":          "completedAt is the time when the update completed",
	"estimatedCompletedAt": "estimatedCompletedAt is the estimated time when the update will complete",
}

func (ClusterVersionProgressInsightStatus) SwaggerDoc() map[string]string {
	return map_ClusterVersionProgressInsightStatus
}

var map_ControlPlaneUpdateVersions = map[string]string{
	"":         "ControlPlaneUpdateVersions contains the original and target versions of the upgrade",
	"previous": "previous is the version of the control plane before the update. When the cluster is being installed for the first time, the version will have a placeholder value '<none>' and carry 'Installation' metadata",
	"target":   "target is the version of the control plane after the update. It may never be '<none>' or have `Installation` metadata",
}

func (ControlPlaneUpdateVersions) SwaggerDoc() map[string]string {
	return map_ControlPlaneUpdateVersions
}

var map_ResourceRef = map[string]string{
	"":          "ResourceRef is a reference to a kubernetes resource, typically involved in an insight",
	"group":     "group of the object being referenced, if any",
	"resource":  "resource of object being referenced",
	"name":      "name of the object being referenced",
	"namespace": "namespace of the object being referenced, if any",
}

func (ResourceRef) SwaggerDoc() map[string]string {
	return map_ResourceRef
}

var map_Version = map[string]string{
	"":         "Version describes a version involved in an update, typically on one side of an update edge",
	"version":  "version is a semantic version string, or a placeholder '<none>' for the special case where this is a \"previous\" version in a new installation, in which case the metadata must contain an item with key 'Installation'",
	"metadata": "metadata is a list of metadata associated with the version. It is a list of key-value pairs. The value is optional and when not provided, the metadata item has boolean semantics (presence indicates true)",
}

func (Version) SwaggerDoc() map[string]string {
	return map_Version
}

var map_VersionMetadata = map[string]string{
	"":      "VersionMetadata is a key:value item assigned to version involved in the update. Value can be empty, then the metadata have boolean semantics (true when present, false when absent)",
	"key":   "key is the name of this metadata value",
	"value": "value is the value for the metadata",
}

func (VersionMetadata) SwaggerDoc() map[string]string {
	return map_VersionMetadata
}

// AUTO-GENERATED FUNCTIONS END HERE
